package ru.sstu.mt.util;

public class NameTransliteration {
    public static String translit(String eng) {
        return eng.replaceAll("ch", "ч")
                .replaceAll("sh", "ш")
                .replaceAll("zj", "ж")
                .replaceAll("ya", "я")
                .replaceAll("yo", "ё")
                .replaceAll("yu", "ю")
                .replaceAll("ye", "у")
                .replaceAll("ee", "и")
                .replaceAll("a", "а")
                .replaceAll("b", "б")
                .replaceAll("c", "ц")
                .replaceAll("d", "д")
                .replaceAll("e", "е")
                .replaceAll("f", "ф")
                .replaceAll("g", "г")
                .replaceAll("h", "х")
                .replaceAll("i", "и")
                .replaceAll("j", "дж")
                .replaceAll("k", "к")
                .replaceAll("l", "л")
                .replaceAll("m", "м")
                .replaceAll("n", "н")
                .replaceAll("o", "о")
                .replaceAll("p", "п")
                .replaceAll("q", "к")
                .replaceAll("r", "р")
                .replaceAll("s", "с")
                .replaceAll("t", "т")
                .replaceAll("u", "у")
                .replaceAll("v", "в")
                .replaceAll("w", "в")
                .replaceAll("x", "кс")
                .replaceAll("y", "и")
                .replaceAll("z", "з")

                .replaceAll("Ch", "Ч")
                .replaceAll("Sh", "Ш")
                .replaceAll("Zj", "Ж")
                .replaceAll("Ya", "Я")
                .replaceAll("Yo", "Ё")
                .replaceAll("Yu", "Ю")
                .replaceAll("Ye", "У")
                .replaceAll("A", "А")
                .replaceAll("B", "Б")
                .replaceAll("C", "Ц")
                .replaceAll("D", "Д")
                .replaceAll("E", "Е")
                .replaceAll("F", "Ф")
                .replaceAll("G", "Г")
                .replaceAll("H", "Х")
                .replaceAll("I", "И")
                .replaceAll("J", "Дж")
                .replaceAll("K", "К")
                .replaceAll("L", "Д")
                .replaceAll("M", "М")
                .replaceAll("N", "Н")
                .replaceAll("O", "О")
                .replaceAll("P", "П")
                .replaceAll("Q", "К")
                .replaceAll("R", "Р")
                .replaceAll("S", "С")
                .replaceAll("T", "Т")
                .replaceAll("U", "У")
                .replaceAll("V", "В")
                .replaceAll("W", "В")
                .replaceAll("X", "Кс")
                .replaceAll("Y", "И")
                .replaceAll("Z", "З");
    }
}
