package ru.sstu.mt.pipeline;

public enum PipelineEvent {
    START,
    PARSE,
    TO_IR,
    INFINITIVES,
    PRE_TRANSFORM,
    TRANSLATE,
    POST_TRANSFORM,
    FORMS_MATCHED,
    TRANSFORM_RUSSIAN,
    FINISHED,
    DICTIONARY,
    SKLONYATOR,
    OPEN_NLP,
    STANFORD_NLP
}
/*
-Dlog_START=NONE -Dlog_PARSE=NONE -Dlog_TO_IR=RESULT -Dlog_INFINITIVES=RESULT -Dlog_PRE_TRANSFORM=RESULT -Dlog_TRANSLATE=RESULT -Dlog_POST_TRANSFORM=RESULT -Dlog_FORMS_MATCHED=RESULT -Dlog_TRANSFORM_RUSSIAN=RESULT -Dlog_FINISHED=NONE -Dlog_DICTIONARY=NONE -Dlog_SKLONYATOR=NONE -Dlog_OPEN_NLP=NONE -Dlog_STANFORD_NLP=EVENT
*/